name: harnishsalon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  charts_flutter:
  cupertino_icons:
  dotted_line:
  flutter_multiselect:
  flutter_rating_bar:
  google_fonts:
  image_picker_gallery_camera: ^0.2.2
  pin_entry_field:
  cached_network_image:
  flutter_styled_toast: ^2.0.0
  shared_preferences:
  flutter_device_type:
  permission_handler:
  multi_image_picker:
  page_transition:
  intl:
  page_view_indicators: 
  flutter_observer: ^1.0.6
  multi_select_flutter: ^4.0.0
  dio:
  firebase_messaging: ^10.0.3
  firebase_core: ^1.3.0
  geolocator: ^7.2.0+1
  geocoder: ^0.2.1
  path_provider: ^2.0.2
  flutter_webview_plugin: ^0.4.0
  flutter_absolute_path: ^1.0.6
  lottie: ^1.1.0
  http: ^0.13.3
  razorpay_flutter: ^1.2.7
  fluttertoast: ^8.0.8
  otp_text_field: ^1.1.1
#  flutter_styled_toast:


dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto Regular
      fonts:
        - asset: assets/Font/Roboto-Regular.ttf

    - family: Roboto Light
      fonts:
        - asset: assets/Font/Roboto-Light.ttf